### PR TITLE
WIP: Paragraphs to any entity type & check entity values of translation

### PR DESCRIPTION
**Pull request by AliagaDev**
Allow attach paragraph to any entity type not just to nodes by "@Given paragraph of :paragraph_type type referenced on the :field_paragraph field of the last :entity_type entity:" step.
Allow entity translation values check by "@Then the :entity_type with field :field_name and value :value translation :langcode should have the following values:" step.

### CODE REVIEW

**Comment by jorgetutor** [comment]
We should avoid continuing the development of the "last entity", it was a workaround that only is needed in some scenarios.
We should locate entities by its label, it is more user friendly and easier to understand to anyone who reads the test

**Comment by mistermoper** [comment]
> We should avoid continuing the development of the "last entity", it was a workaround that only is needed in some scenarios.
> We should locate entities by its label, it is more user friendly and easier to understand to anyone who reads the test

I agree, but not every entity can be looked up by its label, because not every entity has a label. For example: paragraphs does not have a label. If we create a nested paragraph with the 'Given' steps, we couldn't reference them by it's label.

I think we should support both options: looking up the entity with a label (preferred) / last entity (only if it isn't possible do it by label). What do you think?

> Allow attach paragraph to any entity type not just to nodes by "@given paragraph of :paragraph_type type referenced on the :field_paragraph field of the last :entity_type entity:" step.
> Allow entity translation values check by "@then the :entity_type with field :field_name and value :value translation :langcode should have the following values:" step.

Please divide the pull request: one to add the step for the paragraphs, and another to check the values of an entity. Thanks!

**Comment by jorgetutor** [comment]
Understood, I agree with @mistermoper comment

**Comment by AliagaDev** [comment]
Completely agree, here it goes each improvement separately:
https://github.com/Metadrop/behat-contexts/pull/109
https://github.com/Metadrop/behat-contexts/pull/110
https://github.com/Metadrop/behat-contexts/pull/111

**Pull request closed without merging**
