### PR TITLE
Fb organic groups context

### PR DESCRIPTION
**Pull request by OmarMoper**
Hello.

I was using this library to make tests in my Drupal projects.
I needed make steps in order to subscribe user in a organic group. 
So I created a branch with a context which provides methods (no steps) to subscribe user to groups, easy to implement in steps. 

There are 2 methods: one subscribes user in a group, and the other subscribes user and give specific group role.

Can you review this, and merge if you like? Thanks!

### CODE REVIEW

**Comment by OmarMoper** [comment]
By the way, this steps were based in this article http://www.grasmash.com/article/behat-steps-organic-groups. It can helps you to review the context.

**Comment by rsanzante** [comment]
There are no steps defined in this code.

**Comment by OmarMoper** [comment]
I added 2 steps: 


- @Given user :user is subscribed to :group_type group with name :name 
It allows add a user to group with a specific title. For example: Given user "debug" is subscribed to "node" group with name "Node"

- @Given user :user is subscribed to :group_type group with name :name as a :role role(s)
It adds a user to group with specific title, and it add specific group roles. Examples: Given user "debug" is subscribed to "node" group with name "Node" as a "administrator" role; Given user "debug" is subscribed to "node" group with name "Node" as a "administrator,editor" role

Can you review this if you please? Thanks!

**Comment by rsanzante** [comment]
Code is good, but I think steps would be clearer this way:

> 
> Given user "debug" is subscribed to the group of type "node" with name "My Group"
> Given user "debug" is subscribed to group of type "node" group with name "Node" as a(n) "administrator" role(s)

Also, usually groups are nodes. It would be nice to have steps that use 'node' as grup type. Something like this:

> 
> Given user "debug" is subscribed to the group with name "My Group"
> Given user "debug" is subscribed to group group with name "Node" as a(n) "administrator" role(s)

**Comment by OmarMoper** [comment]
I agree, this improves the understanding of the steps.
Changes done, can you review it? thanks!

**Comment by rsanzante** [comment]
Merged, thanks!

**Pull request merged**
